/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaFunctionObj */

#ifndef _Included_com_luajava_LuaFunctionObj
#define _Included_com_luajava_LuaFunctionObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaFunctionObj
 * Method:    callMultipleNative
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_luajava_LuaFunctionObj_callMultipleNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_luajava_LuaFunctionObj
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaFunctionObj_destroyNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
