/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaTable */

#ifndef _Included_com_luajava_LuaTable
#define _Included_com_luajava_LuaTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaTable
 * Method:    getNative
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luajava_LuaTable_getNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_luajava_LuaTable
 * Method:    putNative
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaTable_putNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_luajava_LuaTable
 * Method:    sizeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_luajava_LuaTable_sizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_luajava_LuaTable
 * Method:    keysNative
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_luajava_LuaTable_keysNative
  (JNIEnv *, jobject);

/*
 * Class:     com_luajava_LuaTable
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaTable_destroyNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif