#_LuaJavaNE_version_config
PROJECT_VERSION=2.2.2
PROJECT_NAME=LuaJavaNE
PROJECT_COPYRIGHT=2026_npp-zep
PROJECT_LICENSE=MIT
PROJECT_URL=https://github.com/npp-zep/LuaJavaNE

# JDK 版本要求
MIN_JDK_VERSION=17
RECOMMENDED_JDK_VERSION=17