/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaAgent */

#ifndef _Included_com_luajava_LuaAgent
#define _Included_com_luajava_LuaAgent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaAgent
 * Method:    complete
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaAgent_complete
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
