/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaRuntime */

#ifndef _Included_com_luajava_LuaRuntime
#define _Included_com_luajava_LuaRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaRuntime
 * Method:    callFunctionMultiple
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_luajava_LuaRuntime_callFunctionMultiple
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    bindJavaMethod
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime_bindJavaMethod
  (JNIEnv *, jobject, jstring, jobject, jstring, jobjectArray);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _registerCallback
 * Signature: (JLjava/lang/String;Lcom/luajava/LuaJavaCallback;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime__1registerCallback
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _newState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_LuaRuntime__1newState
  (JNIEnv *, jobject);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _doString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime__1doString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _setGlobal
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime__1setGlobal
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _getGlobal
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_LuaRuntime__1getGlobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _compile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_LuaRuntime__1compile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_LuaRuntime
 * Method:    _doFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaRuntime__1doFile
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
