/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaFunction */

#ifndef _Included_com_luajava_LuaFunction
#define _Included_com_luajava_LuaFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaFunction
 * Method:    callMultiple
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_luajava_LuaFunction_callMultiple
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_luajava_LuaFunction
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaFunction_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
