/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_LuaPromise */

#ifndef _Included_com_luajava_LuaPromise
#define _Included_com_luajava_LuaPromise
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_LuaPromise
 * Method:    complete
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaPromise_complete
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_luajava_LuaPromise
 * Method:    resumeExceptionally
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_LuaPromise_resumeExceptionally
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
